# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-13 07:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ato_children', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gift',
            name='region',
            field=models.IntegerField(choices=[(0, 'Автономна Республіка Крим'), (1, 'Вінницька область'), (2, 'Волинська область'), (3, 'Дніпропетровська область'), (4, 'Донецька область'), (5, 'Житомирська область'), (6, 'Закарпатська область'), (7, 'Запорізька область'), (8, 'Івано-Франківська область'), (9, 'Київська область'), (10, 'Кіровоградська область'), (11, 'Луганська область'), (12, 'Львівська область'), (13, 'Миколаївська область'), (14, 'Одеська область'), (15, 'Полтавська область'), (16, 'Рівненська область'), (17, 'Сумська область'), (18, 'Тернопільська область'), (19, 'Харківська область'), (20, 'Херсонська область'), (21, 'Хмельницька область'), (22, 'Черкаська область'), (23, 'Чернівецька область'), (24, 'Чернігівська область')], default=9),
        ),
        migrations.AlterField(
            model_name='gift',
            name='city',
            field=models.CharField(max_length=32),
        ),
        migrations.DeleteModel(
            name='City',
        ),
    ]
